//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicQueryService.DataSorange
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbInfoMusicEntities1 : DbContext
    {
        public dbInfoMusicEntities1()
            : base("name=dbInfoMusicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumMusical> AlbumMusical { get; set; }
        public virtual DbSet<Artista> Artista { get; set; }
        public virtual DbSet<GeneroMusical> GeneroMusical { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
        public virtual DbSet<SubGeneroMusical> SubGeneroMusical { get; set; }
        public virtual DbSet<SoundtrackArtist> SoundtrackArtist { get; set; }
    }
}
