//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicQueryService.DataSorange
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int IdSong { get; set; }
        public string NombreSong { get; set; }
        public string NombreAlbum { get; set; }
        public Nullable<System.DateTime> FechaInsert { get; set; }
    }
}
